from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ToolCallRequest(BaseModel):
    """A request generated by an agent or planner to invoke a tool."""
    tool_name: str = Field(..., description="Name of the tool to invoke")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Arguments to pass to the tool")

class AgentResponse(BaseModel):
    """Response returned by a single agent execution step."""
    content: str = Field(..., description="The textual response or thinking output")
    tool_calls: List[ToolCallRequest] = Field(default_factory=list, description="Requested tool executions")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metadata")

class PlannerResponse(BaseModel):
    """High-level response returned by the planner containing a list of planned steps."""
    plan_id: str = Field(..., description="Unique ID for this generated plan")
    goal: str = Field(..., description="The user goal that was planned for")
    steps: List[Dict[str, Any]] = Field(default_factory=list, description="The sequence of planned workflow steps")
    confidence: float = Field(default=1.0, description="Confidence score of the generated plan")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata about planning process")
